### ISSUE TITLE
Repeat alarm

### ISSUE THREAD

**Issue by fmarzocca** [DavisNT/mopidy-alarmclock#14]
How can I set the alarm to repeat every morning?
Or, alternatively, how can automatically set an alarmclock from an http call ?

**Comment by DavisNT** [comment]
rgov's fork supports multiple alarms (however it might lack some testing and stability features): https://github.com/rgov/mopidy-alarmclock 

There is no dedicated REST API endpoint however the alarm can be set by sending HTTP POST request to `/alarmclock/set/` with `Content-Type: application/x-www-form-urlencoded` and urlencoded post data that has the folowing fields: 

- `time` with time when to start alarm (e.g. `07:30`) 
- `playlist` with Mopidy URL of the playlist (playlist URLs can be seen in the HTML source of alarm clock page) 
- `random` with value `0` or `1` depending of whether to use Random Track Order 
- `volume` with value from `1` to `100` (obviously small values are not recommended)
- `insec` with value from `0` to `300` determining in how many seconds to increase the volume 

The postdata can also be seen by browser Developer Tools (F12, Network tab, check "Persist Logs"/"Preserve log") while setting the alarm clock from web interface.

**Comment by fmarzocca** [comment]
Thank you
