### ISSUE TITLE
Default settings not showing up

### ISSUE THREAD

**Issue by caffsoul** [DavisNT/mopidy-alarmclock#15]
Hi, 

I have put the below default settings in mopidy.conf (located on mopidy folder) 
for the alarm but even though they are saved I still get the default ones. Am I doing something wrong? 

#def_time = 7:30
#def_playlist =
#def_random = false
#def_volume = 18
#def_vol_inc_duration = 15

![Capture](https://user-images.githubusercontent.com/56960775/67485360-82a3fa80-f672-11e9-967d-f8243ac6c8ed.PNG)

Awesome app btw. I also want to try putting a default URI for a Radio station I would like to wake up to. I have several streams on musicbox and some of them are terrible for early morning.

**Comment by DavisNT** [comment]
The lines starting with `#` character are comments. You need to add something like this to the config file: 

    [alarmclock]
    def_time = 7:30
    def_playlist =
    def_random = false
    def_volume = 18
    def_vol_inc_duration = 15

Regarding proper stream for alarm clock, you need to create a playlist with it as the only song, and specify name of the playlist in `def_playlist` setting.
