### ISSUE TITLE
Doesn't display after installation

### ISSUE THREAD

**Issue by Gimly** [DavisNT/mopidy-alarmclock#18]
Hi,

I've tried installing the extension through pip, but it doesn't seem to work. If I try to get to the URL directly I get a 404 (Iris works, so the HTTP extension is working) and it doesn't show up in the list of HTTP extensions.

Any ideas on how I can find out what might cause the issue?

Thanks

**Comment by DavisNT** [comment]
On what OS and what Mopidy version does this happen? 
Is there anything interesting in Mopidy logs?

**Comment by Gimly** [comment]
I fixed it by installing using

```bash
sudo pip install mopidy-alarmclock
```

Looks like there was a missing dependency that got fixed by sudoing.
