### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by OgLocPlaya** [DavisNT/mopidy-alarmclock#6]
I have installed alarmclock on my raspberry pi musicbox:
`pip install Mopidy-AlarmClock`
when I go to `http://musicbox/alarmclock/` it works, but when I press "Submit" I get:
`500: Internal Server Error`
url: `http://musicbox/alarmclock/set/`
Where could be the problem? what should I do?

**Comment by DavisNT** [comment]
Hi!

What is the version of Mopidy?
Have you restarted Mopidy after installation?
Is anything logged into Mopidy logfiles?

**Comment by VnextIsNotFriendlyAtAll** [comment]
Mopidy 0.19.5
mopidy-alarmclock 0.1.5
I have restarted Raspberry Pi does that count as Mopidy restart?
How do I look to mopidy logs?

P.S. Also I am looking forward to your "sleep" function to turn of music after some time. 
P.S.S. I would like to learn making extensions, I don't know how to see why extensions doesn't work for example if you write bad python code, can you tell me how to debug that/where to find logs? And how to restart extension?

**Comment by DavisNT** [comment]
Restart of Raspberry Pi counts.
Mopidy logs should be located in `/var/log/mopidy`.

P.S. Sleep function will most likely be my top 1 priority for Mopidy AlarmClock.

**Comment by VnextIsNotFriendlyAtAll** [comment]
Ok, I found logs :+1: 

`2016-03-02 23:44:23,536 - ERROR    Uncaught exception POST /alarmclock/set/ (192.168.0.100)
HTTPServerRequest(protocol='http', host='192.168.0.105', method='POST', uri='/alarmclock/set/', version='HTTP/1.1', remote_ip='192.168.0.100', headers=$
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1332, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_alarmclock/http.py", line 53, in post
    playlist = self.core.playlists.lookup(playlist).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 113, in lookup
    uri_scheme = urlparse.urlparse(uri).scheme
  File "/usr/lib/python2.7/urlparse.py", line 140, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 179, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
2016-03-02 23:44:23,565 - ERROR    500 POST /alarmclock/set/ (192.168.0.100) 32.17ms`

P.S. can you tell me how could I restart plugin easily after editing it? without restarting raspberry?

**Comment by DavisNT** [comment]
@VnextIsNotFriendlyAtAll Do you have any playlists available in Mopidy?

**Comment by VnextIsNotFriendlyAtAll** [comment]
No. I installed Mopidy v2.0.0, on this version your extension works without playlist.
So its a bug on v0.19.5 version.

**Comment by DavisNT** [comment]
@VnextIsNotFriendlyAtAll But how the Mopidy-AlarmClock v0.1.5 can wake you up without a playlist?

The current development version contains a feature that an embedded backup alarm sound will go off if the chosen playlist is unavailable (or empty), but this feature has not yet been released...

**Comment by DavisNT** [comment]
The backup alarm feature has been released back in year 2017 and improved in 2018.
However playlist is still needed (as the backup alarm is played only as a backup option).
